---
##### ======================================================================================================= #####
##title          :passwordrest.yml
#description     :This ansible playbook describe create a directory and remove a directory
#author          :santhosh konfdamalla
#date            :20180612
#usage           :ansible-playbook -i hosts create_multiple_directory  --tags=create/delete --ask-sudo-pass
#notes           :TAG-> create: it will create a directory,if the directory does not exits
#notes           :TAG-> delete: it will delete a directory,if the directory exists
#ansible_version :2.5+
##### ======================================================================================================= #####

- hosts: localhost
  become: yes
  gather_facts: no
 
  tasks:
  - name: change the administartor password
    user: 
     name: administrator
     update_password: always
     password: '$6$cpHeW.SKy7N6zS$T5skvS7XSn99RHY8LteQ0na35Na5bthjfJTW.G7waSx/e/eMl5tjQkszsMoTxEwY3ThYogNEnQ8DrVRfRepx/.'
