---
##### ======================================================================================================= #####
##title          :phpnewjoinee.yml
#description     :This ansible playbook describe installing softwares for new joinee
#author          :santhosh kondamalla
#date            :20180618
#usage           :ansible-playbook -i hosts phpnewjoinee --ask-sudo-pass
#ansible_version :2.5+
##### ======================================================================================================= #####
- hosts: localhost
  become: yes
  gather_facts: no
 
  tasks:

  - name: create user in ubuntu 16.04
    user:
     name: vchinnam
     password: '$6$ToE6PskaI4XJgL$IDXSQcpadpVxJJhgH.fc9BcojU/h1aKhx/Xkt2p.6.dOoi1/.lXHoOR3oeAn.Kne1OqTP6rTS0ERdO2Yl6mTL0'
     comment: Vinitha Chinnam
#     groups: sudo
     shell: /bin/bash
#     state: presnt

  
  - name: install apache2
    apt:
     name: apache2
     state: latest

  - name: restart apache2 service
    service: name=apache2 state=restarted

  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: add repo for OpenJDK
    apt_repository: repo='ppa:openjdk-r/ppa' state=present

  - name: ensure apt cache is up to date
    apt: update_cache=yes

  - name: install openJDK7
    apt: name=openjdk-7-jdk state=latest update-cache=yes force=yes
    sudo: yes

  - name: install openJDK8
    apt: name=openjdk-8-jdk state=latest update-cache=yes force=yes
    sudo: yes

  - name: select the latest version of java
    alternatives:
      name: java
      path: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java

  - name: install python-software-properties
    apt: name=python-software-properties state=latest

  - name: add repositary for php5.6
    apt_repository: repo='ppa:ondrej/php' state=present

  - name: ensure apt cache si up to date
    apt: update_cache=yes
   
  - name: install php5.6 
    apt: name=php5.6 state=latest

#  - name: add repositary for filezilla
#    apt_repository: repo='ppa:n-muench/programs-ppa' state=present

  - name: ensure apt cache si up to date
    apt: update_cache=yes
  
  - name: install filezilla
    apt: name=filezilla state=latest

  - name: install sublime text3 gpg image
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: add repositary via command line
    apt_repository:
      repo: deb {{ item.repo }} {{ item.add }}
      state: present
      filename: "{{ item.file }}"

    with_items:
      - repo: https://download.sublimetext.com/
        add: apt/stable/
        file: sublime


  - name: ensure apt cache up to date
    apt: update_cache=yes

  - name: install subline text3 package
    apt: name=sublime-text state=latest

  - name: ensure apt cache up to date
    apt: update_cache=yes


  - name: Download dragon disk image
    get_url: url=http://download.dragondisk.com/dragondisk_1.0.5-0ubuntu_amd64.deb dest=/opt/dragondisk_1.0.5-0ubuntu_amd64.deb
  
  - name : install dependdency packages
    apt: name={{item}}
    with_items:
        - libqt4-dbus
        - libqt4-network
        - libqt4-xml
        - libqtcore4
        - libqtgui4

  - name: install dragondisk
    shell: dpkg -i /opt/dragondisk_1.0.5-0ubuntu_amd64.deb

  - name: ensure packages are installed
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

  - name: ensure apt cache up to date
    apt: name=pgadmin3 state=latest


- hosts: postgres
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbname: localhost
    dbuser: postgres
    dbpassword: postgres

    tasks:
    - name: ensure database is created
      postgresql_db: name={{dbname}}

    - name: ensure user has access to database
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

    - name: ensure no other user can access the database
      postgresql_privs: db={{dbname}} role=PUBLIC type=database priv=ALL state=absent
