---
- hosts: santhosh
  become: yes
  gather_facts: no
  
  tasks:

    - name: Create swap file
      command: dd if=/dev/zero of=/mnt/swap bs=1024 count=1048576
           
      tags:
        - swap.file.create


    - name: Change swap file permissions
      file: path=/mnt/swap
            owner=root
            group=root
            mode=0600
      tags:
         - swap.file.permissions
 

    - name: "Check swap file type"
      command: file /mnt/swap
      register: swapfile
      tags:
        - swap.file.mkswap


    - name: Make swap file
      command: "sudo mkswap /mnt/swap"
      when: swapfile.stdout.find('swap file') == -1
      tags:
        - swap.file.mkswap


    - name: Write swap entry in fstab
      mount: name=none
             src=/mnt/swap
             fstype=swap
             opts=sw
             passno=0
             dump=0
             state=present
      tags:
        - swap.fstab


    - name: Make swap
      command: swapon /mnt/swap
 #     when: ansible_swaptotal_mb < 1
      tags:
        - swap.file.swapon
